# version: '3.9'

services:
  postgres:
    image: postgres:17.4-bookworm
    networks:
      - t2-network
    environment:
      POSTGRES_USER: worker
      POSTGRES_PASSWORD: P@Ssw0rd
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgres_db" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true


  adminer:
    image: adminer:5.0.6-standalone
    restart: always
    ports:
      - 8080:8080
  
  worker:
    image: worker:0.5
    environment:
      - TERM=xterm
      - PG_USER=worker
      - PG_PASSWD=P@Ssw0rd
      - PG_HOST=postgres
      - PG_DBNAME=worker
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always

volumes:
  pgdata:
    driver: local

networks:
  t2-network: